auteur_index:
    path:     /
    defaults: { _controller: "GestionProjetBundle:Auteur:index" }
    methods:  GET

auteur_show:
    path:     /{id}/show
    defaults: { _controller: "GestionProjetBundle:Auteur:show" }
    methods:  GET

auteur_new:
    path:     /new
    defaults: { _controller: "GestionProjetBundle:Auteur:new" }
    methods:  [GET, POST]

auteur_edit:
    path:     /{id}/edit
    defaults: { _controller: "GestionProjetBundle:Auteur:edit" }
    methods:  [GET, POST]

auteur_delete:
    path:     /{id}/delete
    defaults: { _controller: "GestionProjetBundle:Auteur:delete" }
  
    
auteur_modifier:
    path:     /modifier
    defaults: { _controller: "GestionProjetBundle:Auteur:modifier" }    
